#! /bin/bash
###Set your variables

#Device name
device=presto

#Recovery name
recoveryname=cwm

#Recovery version
vernumber=6.0.5.0

#Insert date
NOW=$(date +"%m%d%y")

#File revision
revision=r2

#Author of the file
author=marduk191

#Recovery Image location
recloc=/media/marduk191/b59ee394-ecc6-45b0-b5e6-244bb44528ae/NEW/cm11/target/product/presto/recovery.img

######################################################################################################################################
###################################################END OF CONFIGURATION###############################################################
######################################################################################################################################

#import recovery
cp $recloc ./output/zip

#Import changelogs
rm ./output/zip/META-INF/com/google/android/aroma/changelogs.txt
cp ./changelogs.txt ./output/zip/META-INF/com/google/android/aroma/changelogs.txt

cd output/zip
zip -r -q --exclude=*zip* $device.$recoveryname.recovery.$vernumber.$revision.$NOW-$author.zip * && echo "Success" || echo "Failure"
