#! /bin/bash
device=$(yad --entry --text="Device name")
recoveryname=$(yad --entry --text="Name of Recovery")
vernumber=$(yad --entry --text="Version number")
NOW=$(date +"%m%d%y")
revision=$(yad --entry --text="File revision")
author=$(yad --entry --text="Author name")
recloc=$(yad --entry --text="Enter recovery.img location")
cp $recloc ./output/zip
rm ./output/zip/META-INF/com/google/android/aroma/changelogs.txt
cp ./changelogs.txt ./output/zip/META-INF/com/google/android/aroma/changelogs.txt
cd output/zip
zip -r -q --exclude=*zip* $device.$recoveryname.recovery.$vernumber.$revision.$NOW-$author.zip * && echo "Success" || echo "Failure"
