#!/bin/bash
## Aroma recovery packer
## By marduk191
## email: marduk191@gmail.com
frmdata=$(
	yad --width=400 \
	 --title="Presto Aroma recovery packer - marduk191" \
	 --text="Please enter your details:" \
	 --image="13.jpg" \
	 --form --date-format="%-d %B %Y" --item-separator="," \
	 --field="Device Name:" \
	 --field="Recovery Name:" \
	 --field="Version Number:" \
	 --field="File Revision:" \
	 --field="Author Name:" \
	 --field="recovery image location:FL" \
	 --field="include TWRP theme:CHK" \
	 --button="Build" \
	 "Device name" "Recovery name" "Version" "Revision" "Author" "Recovery location" "Pick a location" TRUE)

device=$(echo $frmdata | awk 'BEGIN {FS="|" } { print $1 }')
recoveryname=$(echo $frmdata | awk 'BEGIN {FS="|" } { print $2 }')
vernumber=$(echo $frmdata | awk 'BEGIN {FS="|" } { print $3 }')
revision=$(echo $frmdata | awk 'BEGIN {FS="|" } { print $4 }')
NOW=$(date +"%m%d%y")
author=$(echo $frmdata | awk 'BEGIN {FS="|" } { print $5 }')
recloc=$(echo $frmdata | awk 'BEGIN {FS="|" } { print $6 }')
themeit=$(echo $frmdata | awk 'BEGIN {FS="|" } { print $7 }')
  
  if [[ "$themeit" == "TRUE" ]]
     then cp -r ./output/theme ./output/zip/theme
     else echo "Theme is not available"
  fi 

notify-send "Presto Recovery Packer									" \
            "Modify your aroma-config and Changelogs. Press ctrl+x and follow the instructions to save changes." \
            -i important
            
pico ./output/zip/META-INF/com/google/android/aroma-config
pico ./changelogs.txt

  if test -e $recloc
     then cp $recloc ./output/zip/
     else echo "Error: set your recovery location"
  fi
  
cp ./changelogs.txt ./output/zip/META-INF/com/google/android/aroma/changelogs.txt
cd output/zip

  if test -e ./recovery.img
     then zip -r -q "$device.$recoveryname.recovery.$vernumber.$revision.$NOW-$author.zip" * 
     else echo "Error: recovery.img not found"
  fi

clear
ls -lh "$device.$recoveryname.recovery.$vernumber.$revision.$NOW-$author.zip"

notify-send "Presto Recovery Packer 									" \
            "Recovery packed!" \
            -i zip


